### ISSUE TITLE
First character not appearing / truncated on Chrome / Edge / Safari

### ISSUE THREAD

**Issue by tagliala** [Choices-js/Choices#1002]
**Describe the bug**
The first character inserted by the user is not correctly visible

**To Reproduce**
1. Go to https://choices-js.github.io/Choices/ with Chrome or Safari
2. Try to insert a character in the first select dropdown
3. The character does not appear or it is truncated 

**Expected behavior**
The first character entered is visible

**Screenshots**
![image](https://user-images.githubusercontent.com/556268/151251530-56d06744-e7ec-4f52-9af2-01cf78d5074b.png)

![image](https://user-images.githubusercontent.com/556268/151251451-d94681fd-37c6-4e61-a671-7547b6fea949.png)

![image](https://user-images.githubusercontent.com/556268/151251778-c8664b6a-290a-40df-b755-9bbd65df8b7c.png)

**Desktop (please complete the following information):**
 - OS: macOS 12.1 / Windows 10
 - Browser: Chrome / Safari / Edge
 - Version 97 / 15.2 / 97

Firefox is not affected on both Win and Mac

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 15.2.1
 - Browser Safari
 - Version 15.2.1

**Comment by mtriff** [comment]
Looks like this is a side-effect of #908. You can fix this with the solution suggested [here](https://medium.com/@rion.mrk/how-to-remove-x-icon-from-search-input-field-or-input-type-search-db3c808405fb) (tested on Chrome, you may need additional markup for Safari).

This will be fixed in the next version.
