### ISSUE TITLE
Search result bug

### ISSUE THREAD

**Issue by quteharry19** [Choices-js/Choices#1032]
search results are not appropriate

**To Reproduce**
add options to html select 

Arvind Mills 
Prakash And Sons
Vardhman
Sarva Foam
Hersheys

now search for amazon

search is giving 3 result and none is definitely not amazon

**Expected behavior**
No results found

**Screenshots**
<img width="901" alt="Screenshot 2022-04-15 at 12 16 21 AM" src="https://user-images.githubusercontent.com/44421422/163457674-bda7d5c6-6eb6-45bd-822f-d4b59bc31d32.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome

**Comment by mtriff** [comment]
Choices.js uses [Fuse.js](https://fusejs.io/), a fuzzy search library, which is why you see results that don't have your `amaz` substring. You can make the search results more specific to your needs by adjusting the options passed to Fuse.js using the `fuseOptions` parameter, as shown in the [setup example](https://github.com/Choices-js/Choices#setup). A full list of options for Fuse.js are available [here](https://fusejs.io/api/options.html).
