### ISSUE TITLE
Searching stops after 30th character of option label

### ISSUE THREAD

**Issue by devnull69** [Choices-js/Choices#1062]
**Describe the bug**
Searching stops after 30th character of option label

**To Reproduce**
Setup a drop down with longer option labels, try to search for a label part that starts after character #31 of the label string. The option will not be retrieved

**Expected behavior**
Search should not be limited to 30 characters ... or rather, it should be configurable

**Desktop (please complete the following information):**
 - Windows 11
 - Chrome
 - Version 106

**Comment by mityukov** [comment]
you may probably try to tinker with `fuseOptions` in order to adjust the search behavior
https://fusejs.io/api/options.html

also, increasing of `searchResultLimit` may be helpful

**Comment by Xon** [comment]
You likely need to adjust the default fuse.js configuration, and read the [scoring theory](https://www.fusejs.io/concepts/scoring-theory.html) for how to adjust the arguments. 

Alternatively import [choices.search-prefix.min.js](https://github.com/Choices-js/Choices/blob/main/public/assets/scripts/choices.search-prefix.min.js) instead of [choices.js](https://github.com/Choices-js/Choices/blob/main/public/assets/scripts/choices.js).

The prefix search will work on any search length, but doesn't handle fuzzy matching.
