### ISSUE TITLE
when connecting via NPM, the select looks open

### ISSUE THREAD

**Issue by NikitinVladimirV** [Choices-js/Choices#1076]
**Describe the bug**
when connecting via NPM, the "select" looks open

**To Reproduce**
1. installed via NPM
2. placed the "select" in HTML
3. imported Choices in main.js
4. wrote in main.js `const element = document.querySelector('.js-choice');
  const choices = new Choices(element);`
5. the "select" looks open

**Expected behavior**
the select must be assembled into one line

**Screenshots**
JS
![image](https://user-images.githubusercontent.com/79249769/204532579-cc3c69c1-4e64-404f-9df0-617a9d95d92a.png)
HTML
![image](https://user-images.githubusercontent.com/79249769/204532622-9ae7884d-6498-4264-b54b-f1501dc00b31.png)
RESULT
![image](https://user-images.githubusercontent.com/79249769/204532658-76f7a1e4-a6e6-4bbb-a1e1-ae986b7aebd8.png)

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [yandex]
 - Version [22.11.0.2500 (64-bit)]

**Comment by BrayanCaro** [comment]
You have several options:

#### Load from a js file

You can add the `choices.css` in `main.js`

```js
import Choices from "choices.js";
import "choices.js/public/assets/styles/choices.css";

const choices = new Choices('.select')
```
#### External CSS file

Let's say you have a CSS file called `style.css`, then you can add the styles:

```css
@import "choices.js/public/assets/styles/choices.css";

/* more css ... */
```

And don't forget to load your stylesheet in your html:
```html
<html>
  <head>
    <!-- more tags ... -->
    <link rel="stylesheet" href="/style.css">
  </head>
  <body>
    <select class="select">
        <option>1</option>
        <option>2</option>
    </select>
    <script type="module" src="/main.js"></script>
  </body>
</html>
```
---
Note you can also use `choices.min.css` instead of `choices.css`. 
And of course, you can use `choices.scss` for more customisation but that is another topic.

**Comment by NikitinVladimirV** [comment]
Thanks! I have already found a solution. Forgot to connect styles "Choices.js")
