### ISSUE TITLE
Do not remove <option>'s inside the <select>.

### ISSUE THREAD

**Issue by EmeraldWeb** [Choices-js/Choices#601]
I really like this library, but there is one unpleasant thing for me - clearing the `<option>` as a result of the library. What prevents future improvements and maintenance through cross-functional scripts.
I don’t know why you don’t save the original tag tree inside `<select>`, if this is necessary, then please add a parameter to preserve the original data structure.

**Comment by jrockowitz** [comment]
I just ran into a [bug in the Webform module for Drupal](https://www.drupal.org/project/webform/issues/3079022) related to `<option>` tags being removed and re-added.  

The bug was related to trying to cache an option element via jQuery (see below) and then having this option element being removed by ChoicesJS. 

`var $otherOption = $element.find('option[value="_other_"]');`

_This is not a major issue and easy to work-around but I felt it was worth noting here._

**Comment by dexcell** [comment]
I also likes the lib, but turns out i can't use this plugin because the choices.js doesn't preserve the select options , so i can't attach html5 data to the option and use it for another js function.
sadly i have to go back to select2 since it does preserve the options.

I hope this will implemented in next version. Ideally choices.js is the interface to a hidden select, but it does not modify the original select tag just like select2.

**Comment by jshjohnson** [comment]
Happy to review a PR that resolves this 👍

**Comment by drcll** [comment]
Is there some update? I'm using version 9.0.1 and the issue still remains.

**Comment by Xon** [comment]
Implemented as part of v11.0.0
