### ISSUE TITLE
setChoices() check for duplicates

### ISSUE THREAD

**Issue by bgp1** [Choices-js/Choices#855]
**Is your feature request related to a problem? Please describe.**
When I have `duplicateItemsAllowed` set to `false` I would expect a check on `setChoices` and if there is a duplicate it not be added to the list.

**Describe the solution you'd like**
When `duplicateItemsAllowed` is `false` do not add in items that are duplicates already entered when adding via `setChoices`

**Describe alternatives you've considered**
Considered custom code to check for this but that seems like too much effort at this time. 

**Additional context**
N/A

**Comment by DanielCoulbourne** [comment]
I'm having an issue with this as well.

Imagine a scenario where I have 3 choices:

```javascript
//  Choices.__currentState.choices
const initialChoices = [
    {label: 'good', value: 'good', selected: false},
    {label: 'bad', value: 'bad', selected: false},
    {label: 'duplicate', value: 'duplicate', selected: true}
];
```

Now I want to remove choice where `value: 'bad'`. Right now the only public API for this is `setChoices` so:

```javascript
const filteredChoices = initialChoices.filter(choice => choice.value !== 'bad')
Choices.setChoices(filteredChoices, 'value', 'label', true)
```

This results in a duplicate copy of the `value: duplicate` issue because it has `selected: true`.

This occurs because of [this line](https://github.com/jshjohnson/Choices/blob/68313da4122ec7f76274b22926e762914c96723d/src/scripts/choices.ts#L2024, which calls `choices._addItem()` when `choices._addChoice()` is called on a choice where `selected: true`

I can see this behavior being okay if `duplicateItemsAllowed: false`, but if it's enabled, my best guess is that 

```javascript
    if (isSelected) {
      this._addItem({
```

could be replaced with 


```javascript
    if (isSelected && this.config.duplicateItemsAllowed) {
      this._addItem({
```

@jshjohnson I'd be happy to open a PR for this if you'd be willing to merge it.

**Comment by christophsaile** [comment]
Is there an update on this issue?
I have the same problem as @DanielCoulbourne. When calling `setChoices()` with `replace: true`, the `addItem` event is triggred which results in the selected item being added twice even though `uplicateItemsAllowed: false`.
