### ISSUE TITLE
Upgrade fuse.js to v6

### ISSUE THREAD

**Issue by paulovieira** [Choices-js/Choices#881]
Fuse.js has seen a couple new major releases recently. I don't know much about what might have changed, but it seems the code is smaller now.

https://github.com/krisk/Fuse/releases

**Comment by Vintic** [comment]
Would be really cool.
Because, for example:
`const options = {
  includeScore: true,
  shouldSort: true,
  threshold: 0.0,
  useExtendedSearch: true,
   ignoreLocation: true,
  keys: [
    "title"
  ]
};

const fuse = new Fuse(list, options);

// Change the pattern
const pattern = "tyu hello asd"

return fuse.search(pattern)`
in 
`[
  {
    "title": "hello zxc qweeee tyu",},
  {
    "title": "hello omg asdddd tyu",}]`
fuse 6 - will return second item.
Current version - will return nothing.
