### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by mectorfector** [Choices-js/Choices#942]
When setting the choices from a JSON file, an error for unhandled promise rejection occurs.

The code to reproduce:
`const choices = new Choices($('.js-choices')[0], {});
choices.setChoices(async () => {
const items = await fetch('./ajaxFileHere.php');
return items.json();
});`

Console logs the following:
**Unhandled Promise Rejection: TypeError: null is not an object (evaluating 't.innerHTML=this._placeholderValue||""')**

Thanks in advance 😄

**Comment by FahriDevZ** [comment]
i think is because the await is not handled, the error is coming from your response giving invalid type.
You must add try/catch to handle the exception, or in promise use .then/.catch.

After this please close and move your question to [stackoverflow](https://stackoverflow.com/questions/tagged/javascript)
