### ISSUE TITLE
Avoid displaying results that do not correspond at all to items list

### ISSUE THREAD

**Issue by sapomuyverde** [Choices-js/Choices#978]
Hi,
Is there any configuration where I can indicate the type of search to be performed, I mean, I want to be able to search in any part of the element, but as shown in the image the searched text does not correspond with the results.

![img](https://user-images.githubusercontent.com/15135396/146663679-655f369b-c28b-440b-b5be-3bf60d575cc0.png)

what I would expect is that since "javier" is not in the list items, it would display a "no results found" message.

**Comment by mtriff** [comment]
All searching is handled by the [Fuse.js](https://github.com/krisk/Fuse) library. We're on an older version of the library, so you can see a list of available options [here](https://github.com/krisk/Fuse/blob/0226926b36e9201f90fc8a5f0584e2d596ab7bae/README.md). We'll be upgrading to the latest version in the near future.

I'd recommend testing with the `threshold` and `location` options. If that doesn't get the results you need, you can provide your own search function via `searchFn`/`getFn` in the current version, or a combination of `getFn` and `useExtendedSearch` when we update to the latest version. Otherwise, questions about using Fuse are best posted on their repo.
